pipeline {
    agent any
    stages {
        stage ('Check Docker') {
            steps {
                sh 'docker ps'
            }
        }
        stage ('Build image') {
           steps {
               sh 'docker build -t my-app-jenkins:${BUILD_NUMBER} ./module2/task7'
           }
        }
    }
}
