pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                sh 'pip3 install pytest --break-system-packages'
            }
        }
        stage('Test') {
            steps {
                sh '/var/jenkins_home/.local/bin/pytest'
            }
        }
    }
}
