pipeline {
   agent {
       kubernetes {
           label 'k8s-agent'
       }
   }
   stages {
       stage('build and push image'){
           steps {
               withCredentials ([
                    usernamePassword (
                        credentialsId: 'docker-hub-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ])  { sh '''
                        apk add --no-cache curl
                        curl -LO "https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz"
                        tar -xzf helm-v3.12.0-linux-amd64.tar.gz
                        mv linux-amd64/helm /usr/local/bin/helm
                        apk add --no-cache docker-cli --repository https://dl-cdn.alpinelinux.org/alpine/edge/community
                        curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
                        chmod +x kubectl
                        mv kubectl /usr/local/bin/
                        docker build -t task10:${BUILD_NUMBER} ./module6
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                        docker tag task10:${BUILD_NUMBER} ${DOCKER_USERNAME}/task10:${BUILD_NUMBER}
                        docker tag task10:${BUILD_NUMBER} ${DOCKER_USERNAME}/task10:latest
                        docker push ${DOCKER_USERNAME}/task10:${BUILD_NUMBER}
                        docker push ${DOCKER_USERNAME}/task10:latest
                      '''
                }
           }
       }
       stage('Check kubectl') {
           steps {
               withCredentials([file(credentialsId: 'kubeconfig-minikube', variable: 'KUBECONFIG')]) {
                   sh 'kubectl version --client'
                   sh 'kubectl get pods'
               }
           }
       }
       stage('Deploy to k8s') {
           steps {
               withCredentials([file(credentialsId: 'kubeconfig-minikube', variable: 'KUBECONFIG')]) {
                   sh 'helm upgrade --install my-app ./module6/helm-charts/my-app-chart --set image.tag=${BUILD_NUMBER}'
               }
           }
       }
   }
}
