pipeline {
   agent {
       docker {
           image 'lachlanevenson/k8s-kubectl:v1.25.0'
           args '--entrypoint ""'
       }
   }
   stages {
       stage('Check kubectl') {
           steps {
               withCredentials([file(credentialsId: 'kubeconfig-minikube', variable: 'KUBECONFIG')]) {
                   sh 'kubectl version --client'
                   sh 'kubectl get pods'
               }
           }
       }
   }
}
