pipeline {
   agent {
       docker {
           image 'lachlanevenson/k8s-kubectl:v1.25.0'
       }
   }
   stages {
       stage('Check kubectl') {
           steps {
               sh 'kubectl version --client'
               sh 'kubectl get pods'
           }
       }
   }
}
